version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://97ravi2002:Mongo1234@cluster0.v84t2di.mongodb.net/food-del
      - JWT_SECRET=random#secret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
